module.exports = [
  { class_id: 2, course_id: 2 },
  { class_id: 2, course_id: 3 },
  { class_id: 2, course_id: 4 },
  { class_id: 3, course_id: 3 },
  { class_id: 3, course_id: 4 },
  { class_id: 4, course_id: 4 },
  { class_id: 4, course_id: 5 },
  { class_id: 4, course_id: 6 },
  { class_id: 4, course_id: 7 },
  { class_id: 5, course_id: 2 },
  { class_id: 5, course_id: 3 },
  { class_id: 6, course_id: 2 },
  { class_id: 6, course_id: 4 },
  { class_id: 6, course_id: 6 },
  { class_id: 7, course_id: 2 },
  { class_id: 7, course_id: 5 },
  { class_id: 7, course_id: 6 },
  { class_id: 8, course_id: 3 },
  { class_id: 8, course_id: 7 },
  { class_id: 9, course_id: 3 },
  { class_id: 9, course_id: 4 },
  { class_id: 9, course_id: 7 },
  { class_id: 10, course_id: 2 },
  { class_id: 10, course_id: 5 },
  { class_id: 10, course_id: 6 }
]