const password = '000000'

module.exports = [{
  // Teachers
  password,
  name: 'Vincent Wen',
  role_id: 1,
  bio: '少就是多，搓就是好，丑就是帅，伦敦烹饪学院优秀毕业生。',
  gender: 1,
  cost: 300,
  place: 'online',
  mobilephone: 18811111111,
  email: 'teacher1@xfolio.cn',
}, {
  password,
  name: 'Peter Pan',
  role_id: 1,
  bio: '从来没有务过正业，十八般武艺，样样精通',
  gender: 0,
  cost: 200,
  province: '31',
  available: 30,
  city: '3101',
  place: 'offline',
  mobilephone: 18822222222,
  email: 'teacher2@xfolio.cn',
}, {
  password,
  name: 'Tony Zhange',
  role_id: 1,
  bio: '建筑设计从入门到出殡',
  gender: 1,
  place: 'online',
  cost: 400,
  active: false,
  province: '11',
  available: 15,
  city: '1101',
  mobilephone: 18833333333,
  email: 'teacher3@xfolio.cn',
}, {
  password,
  name: 'Wang Dachui',
  role_id: 1,
  bio: '智慧树上智慧果，智慧树下你和我',
  gender: 0,
  cost: 999,
  province: '45',
  available: 20,
  city: '4501',
  mobilephone: 18844444444,
  email: 'teacher4@xfolio.cn',
}, {
  // Students
  password,
  name: '小明',
  bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut .',
  gender: 1,
  mobilephone: 17711111111,
  province: '45',
  city: '4503',
  email: 'student1@xfolio.cn',
}, {
  password,
  name: '小东',
  bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut .',
  gender: 0,
  mobilephone: 17722222222,
  province: '22',
  city: '2201',
  email: 'student2@xfolio.cn',
}]
